apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.externalSecret.storeName | quote }}
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      vaultUrl: {{ .Values.externalSecret.vaultUrl | quote }}
      serviceAccountRef:
        name: external-secrets
        namespace: external-secrets
