apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-oauth
  namespace: grafana
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: romaine-kv
    kind: ClusterSecretStore
  target:
    name: grafana-oauth
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      data:
        client-id: {{ "{{ .clientID }}" | quote }}
        client-secret: {{ "{{ .clientSecret }}" | quote }}
  data:
    - secretKey: clientID
      remoteRef:
        key: grafana-oauth-client-id
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
    - secretKey: clientSecret
      remoteRef:
        key: grafana-oauth-client-secret
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
