grafana:
  replicas: 1

  deploymentStrategy:
    type: Recreate

  persistence:
    enabled: true
    type: pvc
    storageClassName: managed-csi
    accessModes:
      - ReadWriteOnce
    size: 10Gi

  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      memory: 512Mi

  admin:
    existingSecret: grafana-admin
    userKey: admin-user
    passwordKey: admin-password

  grafana.ini:
    server:
      domain: grafana.romaine.life
      root_url: https://grafana.romaine.life/
    analytics:
      reporting_enabled: false
      check_for_updates: false
    auth:
      disable_login_form: false
    auth.generic_oauth:
      name: Microsoft
      enabled: true
      allow_sign_up: true
      auto_login: false
      client_authentication: client_secret_post
      scopes: openid email profile
      email_attribute_path: email || preferred_username || upn
      login_attribute_path: preferred_username || email || upn
      name_attribute_path: name
      auth_url: https://login.microsoftonline.com/common/oauth2/v2.0/authorize
      token_url: https://login.microsoftonline.com/common/oauth2/v2.0/token
      api_url: https://graph.microsoft.com/oidc/userinfo
      role_attribute_strict: true
      allow_assign_grafana_admin: false
      skip_org_role_sync: false
      use_pkce: true
    users:
      auto_assign_org: true
      auto_assign_org_role: Admin

  envValueFrom:
    GF_AUTH_GENERIC_OAUTH_CLIENT_ID:
      secretKeyRef:
        name: grafana-oauth
        key: client-id
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET:
      secretKeyRef:
        name: grafana-oauth
        key: client-secret
    GF_AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE_PATH:
      secretKeyRef:
        name: grafana-oauth
        key: role-attribute-path

  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Loki
          type: loki
          access: proxy
          url: http://loki-gateway.loki.svc.cluster.local
          isDefault: true
          jsonData:
            maxLines: 1000

  testFramework:
    enabled: false
