grafana:
  replicas: 1

  persistence:
    enabled: true
    type: pvc
    storageClassName: managed-csi
    accessModes:
      - ReadWriteOnce
    size: 10Gi

  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      memory: 512Mi

  admin:
    existingSecret: grafana-admin
    userKey: admin-user
    passwordKey: admin-password

  grafana.ini:
    server:
      domain: grafana.romaine.life
      root_url: https://grafana.romaine.life/
    analytics:
      reporting_enabled: false
      check_for_updates: false
    auth:
      disable_login_form: true
    auth.azuread:
      name: Entra ID
      enabled: true
      allow_sign_up: true
      auto_login: false
      client_authentication: client_secret_post
      scopes: openid email profile
      auth_url: https://login.microsoftonline.com/2236b5e4-81d2-4d82-bde5-17b1037999ea/oauth2/v2.0/authorize
      token_url: https://login.microsoftonline.com/2236b5e4-81d2-4d82-bde5-17b1037999ea/oauth2/v2.0/token
      allowed_organizations: 2236b5e4-81d2-4d82-bde5-17b1037999ea
      role_attribute_strict: false
      allow_assign_grafana_admin: false
      skip_org_role_sync: false
      use_pkce: true
    users:
      auto_assign_org: true
      auto_assign_org_role: Admin

  envValueFrom:
    GF_AUTH_AZUREAD_CLIENT_ID:
      secretKeyRef:
        name: grafana-oauth
        key: client-id
    GF_AUTH_AZUREAD_CLIENT_SECRET:
      secretKeyRef:
        name: grafana-oauth
        key: client-secret

  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Loki
          type: loki
          access: proxy
          url: http://loki-gateway.loki.svc.cluster.local
          isDefault: true
          jsonData:
            maxLines: 1000

  testFramework:
    enabled: false
